spring:
  profiles: dev
properties:
  spring.activemq.broker-url: tcp://localhost:61616
  spring.activemq.user: admin
  spring.activemq.password: admin
  spring.activemq.pool.enabled: false
---
spring:
  profiles: test
properties:
  spring.activemq.broker-url: tcp://localhost:61616
  spring.activemq.user: admin
  spring.activemq.password: admin
  spring.activemq.pool.enabled: false